### ISSUE TITLE
Error with blank URL list

### ISSUE THREAD

**Issue by ieee8023** [AcademicTorrents/at-python#20]
```
import academictorrents as at
file = at.get("4d563087fb327739d7ec9ee9a0d32c4cb8b0355e")
```
I get this error

MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

In the torrent the url list looks like this (using http://academictorrents.com/torrentexplorer/): 

```
    "url-list": [
        ""
    ]
```

**Comment by mweiss17** [comment]
Fixed in PR: https://github.com/AcademicTorrents/at-python/pull/21

added a test for it, too.
