### ISSUE TITLE
Sometimes get request hang

### ISSUE THREAD

**Issue by ieee8023** [AcademicTorrents/at-python#22]
When downloading it will just hang at 99.9% or 100%

![screen shot 2019-01-08 at 3 59 06 pm](https://user-images.githubusercontent.com/446367/50858431-668ed100-135e-11e9-8ba4-bf447d423657.png)

**Comment by mweiss17** [comment]
oh that's not great. I'll look into it.

I'm digging that 47MB/s though

**Comment by mweiss17** [comment]
I have not recently observed this behaviour, if it is observed again, please reopen this
