### ISSUE TITLE
Windows '/tmp' conflict

### ISSUE THREAD

**Issue by logasja** [academictorrents/at-python#31]
I run on windows 10 as well as linux for my workload and the only problem I have here is that the download attempts to put the torrent into the /tmp folder which doesn't exist on Windows.

**Comment by mweiss17** [comment]
I don't really have access to a windows machine, but it sounds like the necessary fix is fairly straightforward. We'll just need to check if it exists, and if not make it. 

I'm currently involved in a crash project related to COVID-19, so I don't have time to write any other code, but if a PR was submitted with the change I'd merge it.
