### ISSUE TITLE
Misplaced "total length" and "downloaded length"

### ISSUE THREAD

**Issue by lytning98** [academictorrents/at-python#32]
https://github.com/academictorrents/at-python/blob/350705b4b3cd3e23beba61ff452d48f219bd4930/academictorrents/Client.py#L48

It seems that "total length" and "downloaded length" were misplaced in this line of code. I got `Total length 0   Downloaded xxx` at the beginning of downloading.

**Comment by ieee8023** [comment]
Fixed thanks!
