### ISSUE TITLE
Command line interface?

### ISSUE THREAD

**Issue by tholop** [academictorrents/at-python#33]
Is there a way to execute `at.get` directly from the command line? It could be more convenient than having to launch a Python terminal, import the package and run `at.get(...)`.

If there isn't, I'm happy to open a PR and start working on a wrapper. Maybe something with Typer or Click, or at least a `__main__` to make the package executable.

**Comment by ieee8023** [comment]
There is the `simple_client.py` in the examples folder. If you want to make a command line tool that is in the user's path after they pip install it then that would be great! (I don't know how to do that with pip).

**Comment by tholop** [comment]
Thanks, I opened a PR here: https://github.com/academictorrents/at-python/pull/34
