### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by artttt** [academictorrents/at-python#38]
Hi,
Im running this.
```
import academictorrents
path = academictorrents.get(
    "a3ce54e3de8177011a3c6e1b9ed130e0467c3f4e", datastore="~/academictorrents-datastore"
)
```
and seeing memory usage steadily increasing over time resulting in python crashing after something like 30 - 60 minutes.

Machine its running on has 32gb of ram.

It uses about 50% of the ram quite quickly early on and then slowly increases after that.

I currently have locally about 10% of the torrent. I think it is crashing more regularly as I get more of the torrent but i've not paid enough attention to be sure.

**Comment by ieee8023** [comment]
This is likely true as this library hasn't been maintained. I would recommend using [aria2c](https://aria2.github.io/)

**Comment by artttt** [comment]
Thanks for letting me know.

Can I suggest an update to the readme with this info.
