### ISSUE TITLE
Add option to fail to a url if the torrent doesn't work or add it as a webseed

### ISSUE THREAD

**Issue by ieee8023** [AcademicTorrents/at-python#5]
Situation: The AT server is not accessible/blocked/broken. The user should be able to specify a URL so that the download will succeed.

Situation: The API is failing to run. We should catch some error that happened at a high level and just fail over to the URL and download it without checking hashes.

Situation: Everything is fine but the user would like to specify an extra webseed URL that may be internal to a network or contain a special URL (with a password).

All these situations are covered if we allow the user to call the API like this:

at.get("66450ba52ba3f83fbf82ef9c91f2bde0e845aba9", "https://openi.nlm.nih.gov/imgs/collections/NLMCXR_reports.tgz")

Hopefully this doesn't overlap any other parameters. If so we can have it as a named argument like: 

at.get("66450ba52ba3f83fbf82ef9c91f2bde0e845aba9", url="https://openi.nlm.nih.gov/imgs/collections/NLMCXR_reports.tgz")

And just for good measure we can also offer a list of URLs:

at.get("66450ba52ba3f83fbf82ef9c91f2bde0e845aba9", url=["https://openi.nlm.nih.gov/imgs/collections/NLMCXR_reports.tgz", "https://some-other-server/NLMCXR_reports.tgz"])

**Comment by mweiss17** [comment]
The interface is and option urls argument:
`at.get(datastore="~/whatever", urls=["https://whatever.com/"])`

Doesn't currently handle string input, but if you put array braces around it it's fine. Also added a little test for it in tests/test_academictorrents.py

https://github.com/AcademicTorrents/at-python/pull/181
